sansis_core_sandbox_homepage:
    pattern:  /
    defaults: { _controller: SanSISCoreSandboxBundle:Default:index }
    
sansis_core_sandbox_search:
    pattern:  /search
    defaults: { _controller: SanSISCoreSandboxBundle:Default:search }
    
sansis_core_sandbox_create:
    pattern: /create
    defaults: { _controller: SanSISCoreSandboxBundle:Default:create }
    
sansis_core_sandbox_edit:
    pattern: /edit
    defaults: { _controller: SanSISCoreSandboxBundle:Default:edit }
    
sansis_core_sandbox_save:
    pattern: /save
    defaults: { _controller: SanSISCoreSandboxBundle:Default:save }
    
sansis_core_sandbox_view:
    pattern: /view
    defaults: { _controller: SanSISCoreSandboxBundle:Default:view }
    
sansis_core_sandbox_delete:
    pattern: /delete
    defaults: { _controller: SanSISCoreSandboxBundle:Default:delete }

sansis_core_sandbox_doctrine_test:
    pattern: /doctrineTest
    defaults: { _controller: SanSISCoreSandboxBundle:DoctrineTest:index }

sansis_core_sandbox_angular_test:
    pattern: /angularTest
    defaults: { _controller: SanSISCoreSandboxBundle:AngularTest:index }

sansis_core_sandbox_angular_get_json_exemplo:
    pattern: /angularTest/getJsonExemplo
    defaults: { _controller: SanSISCoreSandboxBundle:AngularTest:getJsonExemplo }
    options:
            expose: true
