parameters:
    sansis_core_sandbox.cadastrante.class: SanSIS\Core\SandboxBundle\Service\CadastranteService

services:
   sansis_core_sandbox.cadastrante:
        class: %sansis_core_sandbox.cadastrante.class%
        arguments: ["@doctrine.orm.entity_manager", "sandbox"]
