parameters:
#    san_sis_core_sandbox.example.class: SanSIS\Core\SandboxBundle\Example

services:
#    san_sis_core_sandbox.example:
#        class: %san_sis_core_sandbox.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
